site_name: ÂµServerless
nav:
  - Lambda Configuration: 01-lambda-configuration.md
  - Lambda Handlers: 02-handlers.md
  - Dealing with Exceptions: 03-dealing-with-exceptions.md
  - Logging and Metrics: 04-logging.md
  - Event listeners: 05-event-listeners.md
theme: readthedocs